<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Expr.NativeAot</AssemblyName>
    <RootNamespace>Expr.NativeAot</RootNamespace>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <IsAotCompatible>true</IsAotCompatible>
    <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Expr/Expr.csproj" />
  </ItemGroup>
</Project>
